# Generated by Django 4.0.6 on 2022-07-28 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmuebleslist_app', '0005_comentario_comentario_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='edificacion',
            name='avg_calificacion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='edificacion',
            name='number_calificacion',
            field=models.IntegerField(default=0),
        ),
    ]
